name: dartrs
version: 0.2.0
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Simple Restful server implementation
homepage: https://github.com/dkornishev/dartrs
dependencies:
  logging: 0.8.2
  logging_handlers: 0.5.0+3
dev_dependencies:
  unittest: 0.8.4
