name: dartrs
author: Danil Kornishev <danil.kornishev@gmail.com>
version: 0.7.0
homepage: https://github.com/dkornishev/dartrs
description: Simple Restful server implementation
dependencies:
  log4dart: '>=1.4.8 <1.5.0'
dev_dependencies:
  unittest: '>=0.8.5 <0.9.0'
