name: dartrs
version: 0.2.0
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Simple Restful server implementation
homepage: https://github.com/dkornishev/dartrs
dependencies:
  logging: ">=0.8.5 <0.9.0"
  logging_handlers: any
  utf: any
dev_dependencies:
  unittest: ">=0.8.5 <0.9.0"
 