name: dartrs
version: 0.4.0
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Simple Restful server implementation
homepage: https://github.com/dkornishev/dartrs
dependencies:
  log4dart: '>=1.4.8 <1.5.0'
  utf: '>=0.8.5 <0.9.0'
dev_dependencies:
  unittest: '>=0.8.5 <0.9.0'
