name: dartrs
version: 0.2.1
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Simple Restful server implementation
homepage: https://github.com/dkornishev/dartrs
dependencies:
  logging: ">=0.8.5 <0.9.0"
  logging_handlers: any
  utf: any
dev_dependencies:
  unittest: ">=0.8.5 <0.9.0"
<<<<<<< HEAD
 
=======
 
>>>>>>> 8a1e7f6d0bb15c3cc49adf025c445dae0f2a5ee3
